# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false
after_success:
  # push coverage results to Coveralls
  - julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("MittagLeffler")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
